[project]
name = "gavriel-dorfman-mana-bio"
version = "0.1.0"
description = "Take home assignment for mana.bio, by Gavriel Dorfman"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "polars",
    "openpyxl",
    "flask",
    "pytest"
]
